"""
Write local species metadata to app/species_info.json.
"""

from __future__ import annotations

import json
from pathlib import Path


SPECIES_INFO = {
    "Asiatic Lion": {
        "scientific_name": "Panthera leo persica",
        "iucn_status": "Endangered",
        "habitat": "Dry deciduous forest, scrub forest, and savanna-like grasslands.",
        "distribution": "Primarily in and around Gir landscape, Gujarat.",
        "diet": "Large herbivores such as deer, antelope, and livestock when conflict occurs.",
        "fun_fact": "The Asiatic lion is the only wild lion population left in Asia.",
        "summary": "A smaller-maned lion subspecies with a highly restricted range in western India.",
    },
    "Asiatic Wildcat": {
        "scientific_name": "Felis lybica ornata",
        "iucn_status": "Least Concern",
        "habitat": "Arid scrublands, grasslands, and semi-desert regions.",
        "distribution": "Northwestern and central parts of the Indian subcontinent.",
        "diet": "Rodents, birds, reptiles, and small mammals.",
        "fun_fact": "Its coat pattern helps it blend into dry grass and sandy terrain.",
        "summary": "A small wild feline adapted to open, dry landscapes and elusive hunting.",
    },
    "Barking Deer": {
        "scientific_name": "Muntiacus muntjak",
        "iucn_status": "Least Concern",
        "habitat": "Dense forests, bamboo thickets, and woodland edges.",
        "distribution": "Widely distributed in forested parts of India.",
        "diet": "Leaves, shoots, fruits, seeds, and occasionally animal matter.",
        "fun_fact": "It is called barking deer because its alarm call sounds like a bark.",
        "summary": "A shy forest deer known for its solitary habits and dog-like alarm call.",
    },
    "Barasingha": {
        "scientific_name": "Rucervus duvaucelii",
        "iucn_status": "Vulnerable",
        "habitat": "Wet grasslands, floodplains, and swampy meadows.",
        "distribution": "Fragmented populations in northern and central India.",
        "diet": "Grasses, aquatic plants, and tender shoots.",
        "fun_fact": "Its name means twelve-tined deer, referring to the branching antlers of mature males.",
        "summary": "A large swamp deer strongly associated with tall grasslands and marshy habitats.",
    },
    "Bengal Fox": {
        "scientific_name": "Vulpes bengalensis",
        "iucn_status": "Least Concern",
        "habitat": "Grasslands, scrublands, and semi-arid plains.",
        "distribution": "Widely distributed across the Indian subcontinent.",
        "diet": "Insects, rodents, reptiles, fruits, and small birds.",
        "fun_fact": "Its bushy tail often has a distinct dark tip.",
        "summary": "A small native fox of open country, often seen in dry plains and scrub.",
    },
    "Bengal Tiger": {
        "scientific_name": "Panthera tigris tigris",
        "iucn_status": "Endangered",
        "habitat": "Tropical forests, mangroves, grasslands, and swamp forests.",
        "distribution": "Across several tiger landscapes in India, including central, Himalayan foothill, and Sundarbans regions.",
        "diet": "Large ungulates such as deer, wild boar, gaur, and occasionally livestock.",
        "fun_fact": "India holds the largest wild population of Bengal tigers in the world.",
        "summary": "A powerful striped apex predator and one of India’s best-known flagship species.",
    },
    "Blackbuck": {
        "scientific_name": "Antilope cervicapra",
        "iucn_status": "Least Concern",
        "habitat": "Open grasslands, scrublands, and lightly wooded plains.",
        "distribution": "Scattered populations in northwestern, central, and southern India.",
        "diet": "Grasses, pods, flowers, and crops.",
        "fun_fact": "Adult males develop striking dark coats and spiralled horns.",
        "summary": "A swift antelope of open country known for speed, agility, and strong sexual dimorphism.",
    },
    "Bonnet Macaque": {
        "scientific_name": "Macaca radiata",
        "iucn_status": "Least Concern",
        "habitat": "Forests, temple groves, villages, and urban edges.",
        "distribution": "Primarily peninsular southern India.",
        "diet": "Fruits, seeds, leaves, insects, and food scraps near people.",
        "fun_fact": "Its hair radiates outward from the crown, giving it a bonnet-like look.",
        "summary": "A familiar southern Indian monkey that adapts readily to both natural and human-dominated landscapes.",
    },
    "Chinkara": {
        "scientific_name": "Gazella bennettii",
        "iucn_status": "Least Concern",
        "habitat": "Deserts, scrublands, and dry grasslands.",
        "distribution": "Western and central India, especially Rajasthan and Gujarat.",
        "diet": "Grasses, herbs, leaves, and shrubs.",
        "fun_fact": "Chinkara can survive with very little free-standing water.",
        "summary": "Also called the Indian gazelle, this nimble antelope is built for arid habitats.",
    },
    "Chital": {
        "scientific_name": "Axis axis",
        "iucn_status": "Least Concern",
        "habitat": "Moist and dry deciduous forests, grasslands, and woodland edges.",
        "distribution": "Widespread across much of India.",
        "diet": "Grasses, leaves, fruits, and tender shoots.",
        "fun_fact": "The chital keeps its white spots throughout life.",
        "summary": "A highly recognizable spotted deer and one of India's most common ungulates.",
    },
    "Dhole": {
        "scientific_name": "Cuon alpinus",
        "iucn_status": "Endangered",
        "habitat": "Forests, scrub, and hilly landscapes with adequate prey.",
        "distribution": "Patchy populations across central, southern, and northeastern India.",
        "diet": "Medium-sized ungulates and other vertebrate prey.",
        "fun_fact": "Dholes are highly social hunters that often work cooperatively in packs.",
        "summary": "An endangered wild canid known for reddish fur, teamwork, and energetic pack hunting.",
    },
    "Four Horned Antelope": {
        "scientific_name": "Tetracerus quadricornis",
        "iucn_status": "Vulnerable",
        "habitat": "Dry deciduous forests, hilly terrain, and open woodland.",
        "distribution": "Patchy distribution across central and southern India.",
        "diet": "Grass, leaves, flowers, and fruit.",
        "fun_fact": "It is the only living antelope species with four horns.",
        "summary": "A shy and uncommon antelope known for its unusual horn arrangement.",
    },
    "Ganges River Dolphin": {
        "scientific_name": "Platanista gangetica",
        "iucn_status": "Endangered",
        "habitat": "Large freshwater river systems with deep channels and confluences.",
        "distribution": "Ganga-Brahmaputra river basin in northern India.",
        "diet": "Fish, crustaceans, and other aquatic prey.",
        "fun_fact": "It relies heavily on echolocation because its vision is very limited.",
        "summary": "A freshwater dolphin adapted to turbid rivers and an important indicator of river health.",
    },
    "Gaur": {
        "scientific_name": "Bos gaurus",
        "iucn_status": "Vulnerable",
        "habitat": "Evergreen, semi-evergreen, and moist deciduous forests.",
        "distribution": "Western Ghats, central India, and parts of the northeast.",
        "diet": "Grasses, bamboo, leaves, and shoots.",
        "fun_fact": "Gaur is the largest wild bovine in the world.",
        "summary": "A massive forest bovid with a muscular build and distinctive white-stockinged legs.",
    },
    "Golden Jackal": {
        "scientific_name": "Canis aureus",
        "iucn_status": "Least Concern",
        "habitat": "Scrubland, agricultural edges, wetlands, and open country.",
        "distribution": "Found across much of India.",
        "diet": "Omnivorous: small vertebrates, carrion, insects, and fruit.",
        "fun_fact": "Golden jackals are highly adaptable and often thrive near human-altered landscapes.",
        "summary": "A versatile canid that occupies a wide range of habitats across the subcontinent.",
    },
    "Golden Langur": {
        "scientific_name": "Trachypithecus geei",
        "iucn_status": "Endangered",
        "habitat": "Tropical and subtropical forests near river valleys and foothills.",
        "distribution": "Restricted range in western Assam and adjoining Bhutan.",
        "diet": "Leaves, fruits, flowers, seeds, and buds.",
        "fun_fact": "Its pale golden coat makes it one of the most visually distinctive Indian primates.",
        "summary": "A rare leaf-eating monkey with a highly limited range and striking golden fur.",
    },
    "Greater Bandicoot Rat": {
        "scientific_name": "Bandicota indica",
        "iucn_status": "Least Concern",
        "habitat": "Agricultural fields, wetlands, villages, and urban margins.",
        "distribution": "Many parts of the Indian subcontinent.",
        "diet": "Grains, roots, fruits, insects, and discarded food.",
        "fun_fact": "It is a strong burrower and can become a serious agricultural pest.",
        "summary": "A large rodent that thrives in cultivated and human-modified landscapes.",
    },
    "Hanuman Langur": {
        "scientific_name": "Semnopithecus entellus",
        "iucn_status": "Least Concern",
        "habitat": "Forests, rocky outcrops, temple grounds, and urban fringes.",
        "distribution": "Widespread across much of India.",
        "diet": "Leaves, fruits, flowers, bark, and cultivated crops.",
        "fun_fact": "Hanuman langurs spend much of the day feeding on leaves and social grooming.",
        "summary": "A familiar grey langur that is highly adaptable and widely distributed in India.",
    },
    "Honey Badger": {
        "scientific_name": "Mellivora capensis",
        "iucn_status": "Least Concern",
        "habitat": "Grasslands, dry forests, and semi-arid regions.",
        "distribution": "Scattered parts of northwestern, central, and peninsular India.",
        "diet": "Small vertebrates, insects, reptiles, eggs, roots, and honey.",
        "fun_fact": "Honey badgers are famous for their bold behavior and strong digging ability.",
        "summary": "A tough, low-slung mustelid with a broad diet and strong defensive instincts.",
    },
    "Indian Elephant": {
        "scientific_name": "Elephas maximus indicus",
        "iucn_status": "Endangered",
        "habitat": "Grasslands, moist deciduous forests, evergreen forests, and forest edges.",
        "distribution": "Northeast India, central-eastern fragments, and the Western and Eastern Ghats.",
        "diet": "Grasses, bark, leaves, fruits, roots, and cultivated crops.",
        "fun_fact": "An adult elephant can spend most of its waking hours feeding.",
        "summary": "A large and intelligent herbivore central to many Indian forest ecosystems.",
    },
    "Indian Flying Fox": {
        "scientific_name": "Pteropus medius",
        "iucn_status": "Least Concern",
        "habitat": "Woodlands, orchards, riverine trees, and urban roost sites.",
        "distribution": "Widespread across India.",
        "diet": "Fruit, nectar, flowers, and plant juices.",
        "fun_fact": "It is one of the largest fruit bats in South Asia.",
        "summary": "A large fruit bat that plays an important role in pollination and seed dispersal.",
    },
    "Indian Giant Squirrel": {
        "scientific_name": "Ratufa indica",
        "iucn_status": "Least Concern",
        "habitat": "Moist deciduous, semi-evergreen, and evergreen forests.",
        "distribution": "Mainly central and peninsular India, including the Western Ghats.",
        "diet": "Fruits, nuts, bark, flowers, and insects.",
        "fun_fact": "Its fur can show rich shades of maroon, tan, cream, and dark brown.",
        "summary": "A vividly colored tree squirrel that spends most of its life in the forest canopy.",
    },
    "Indian Grey Mongoose": {
        "scientific_name": "Urva edwardsii",
        "iucn_status": "Least Concern",
        "habitat": "Scrublands, farmland edges, forests, and settlements.",
        "distribution": "Widespread across India.",
        "diet": "Rodents, reptiles, insects, eggs, and fruits.",
        "fun_fact": "It is famous for agility and quick reflexes when tackling venomous snakes.",
        "summary": "A bold and adaptable mongoose commonly found in both wild and human-dominated habitats.",
    },
    "Indian Leopard": {
        "scientific_name": "Panthera pardus fusca",
        "iucn_status": "Vulnerable",
        "habitat": "Forests, hills, scrublands, and even peri-urban edges.",
        "distribution": "Widely distributed across India.",
        "diet": "Deer, wild boar, primates, livestock, and other medium-sized prey.",
        "fun_fact": "Leopards are among the most adaptable big cats in India.",
        "summary": "A powerful and elusive big cat able to survive in varied Indian landscapes.",
    },
    "Indian Palm Squirrel": {
        "scientific_name": "Funambulus palmarum",
        "iucn_status": "Least Concern",
        "habitat": "Gardens, plantations, open woodlands, and towns.",
        "distribution": "Common in many parts of peninsular India.",
        "diet": "Seeds, fruits, nuts, tender shoots, and insects.",
        "fun_fact": "Its striped back makes it one of the easiest small mammals to recognize around homes and parks.",
        "summary": "A small striped squirrel often seen darting through trees, walls, and gardens.",
    },
    "Jungle Cat": {
        "scientific_name": "Felis chaus",
        "iucn_status": "Least Concern",
        "habitat": "Wetlands, reed beds, scrub, and agricultural fringes.",
        "distribution": "Across many parts of India except the highest elevations.",
        "diet": "Rodents, birds, frogs, and reptiles.",
        "fun_fact": "Despite its name, the jungle cat is often found in open wetlands and grasslands.",
        "summary": "A medium-sized wild cat with long legs and a preference for dense ground cover.",
    },
    "Nilgai": {
        "scientific_name": "Boselaphus tragocamelus",
        "iucn_status": "Least Concern",
        "habitat": "Open woodland, scrub, farmland edges, and grasslands.",
        "distribution": "Northern, western, and central India.",
        "diet": "Grasses, herbs, leaves, buds, and crops.",
        "fun_fact": "Nilgai is the largest antelope in Asia.",
        "summary": "A large antelope of open country, commonly seen in agricultural mosaics and scrub.",
    },
    "Ruddy Mongoose": {
        "scientific_name": "Herpestes smithii",
        "iucn_status": "Least Concern",
        "habitat": "Forests, scrublands, and rocky areas.",
        "distribution": "Mainly peninsular India and Sri Lanka.",
        "diet": "Insects, reptiles, small mammals, birds, and eggs.",
        "fun_fact": "Its reddish coat and dark tail tip help distinguish it from other mongooses.",
        "summary": "A terrestrial mongoose often found foraging in scrub and lightly wooded habitats.",
    },
    "Striped Hyena": {
        "scientific_name": "Hyaena hyaena",
        "iucn_status": "Near Threatened",
        "habitat": "Dry scrublands, semi-deserts, rocky terrain, and open woodland.",
        "distribution": "Northwestern, central, and parts of peninsular India.",
        "diet": "Carrion, small vertebrates, fruit, and refuse.",
        "fun_fact": "The long mane on its neck and back can stand upright when threatened.",
        "summary": "A mostly nocturnal scavenger with a distinctive sloping back and striped coat.",
    },
    "Wild Boar": {
        "scientific_name": "Sus scrofa cristatus",
        "iucn_status": "Least Concern",
        "habitat": "Forests, wetlands, agricultural landscapes, and grasslands.",
        "distribution": "Widely distributed across India.",
        "diet": "Roots, tubers, fruits, invertebrates, carrion, and crops.",
        "fun_fact": "Wild boar use their snouts to root through soil in search of food.",
        "summary": "A hardy and highly adaptable omnivore found in a wide range of Indian habitats.",
    },
}


def main() -> None:
    output_path = Path("app/species_info.json")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as handle:
        json.dump(SPECIES_INFO, handle, indent=2, ensure_ascii=True)
    print(f"Wrote metadata for {len(SPECIES_INFO)} species to {output_path}")


if __name__ == "__main__":
    main()
